#!/bin/bash
gcc -lm -shared -o _gocr_py.so pgm2asc.o box.o database.o detect.o barcode.o lines.o list.o ocr0.o ocr0n.o ocr1.o otsu.o output.o pixel.o unicode.o remove.o pnm.o pcx.o progress.o job.o gocr_wrap.o gocr.o
